[project]
name = "obmms"
version = "0.1.0"
description = "A demo for OceanBase multi-model search"
authors = [
    {name = "shanhaikang.shk", email = "shanhaikang.shk@oceanbase.com"}
]
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dashscope>=1.20.12",
    "pydantic>=2.9.2",
    "pytest>=8.3.3",
    "pandas>=2.2.3",
    "pyobvector==0.1.18",
    "tqdm>=4.66.6",
    "streamlit>=1.40.0",
    "folium>=0.18.0",
    "streamlit-folium>=0.23.1",
    "python-dotenv>=0.9.9",
]

[tool.uv]
package = true

[[tool.uv.index]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
